# @package _global_

# === 1. Set config parameters ===
name: "" # default name for the experiment, "" means logger (eg. wandb) will generate a unique name
seed: 52 # seed for random number generators in pytorch, numpy and python.random
num_workers: 16 # number of subprocesses to use for data loading.

# === 2. Specify defaults here. Defaults will be overwritten by equivalently named options in this file ===
defaults:
  - env: default
  - dataset: cath
  - features: ca_seq
  - encoder: egnn
  - decoder: default
  - transforms: none
  - callbacks: default
  - optimiser: adam
  - scheduler: none
  - trainer: gpu
  - extras: default
  - hydra: default
  - metrics: none
  - task: inverse_folding # See: /proteinworkshop/config/task/
  - logger: wandb # wandb, tensorboard, csv
  - finetune: default # Specifies finetuning config. See: proteinworkshop/config/finetune/
  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null
  - optional hparams: ${encoder}_${features}
  - _self_ # see: https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/. Adding _self_ at bottom means values in this file override defaults.

task_name: "finetune"

#compile: True
compile: False

# simply provide checkpoint path to resume training
ckpt_path: null
